### ISSUE TITLE
Data source time field not found

### ISSUE THREAD

**Issue by tuapuikia** [CorpGlory/grafana-datasource-kit#90]
Hi,

I'm testing latest hastic server version with ES data source. I'm getting following error and it is from grafana-datasource-kit library. Should I use different timestamp field?

My setup,
Elasticsearch : 7.6.0
Hastic server: 0.3.8

hastic-server-0 hastic-server query time range: from Fri Mar 06 2020 13:37:27 GMT+0000 (UTC) to Fri Mar 06 2020 16:37:27 GMT+0000 (UTC)
hastic-server-0 hastic-server Error: datasource time field not found
hastic-server-0 hastic-server     at /var/www/server/dist/server.js:9:165359
hastic-server-0 hastic-server     at Generator.next (<anonymous>)
hastic-server-0 hastic-server     at s (/var/www/server/dist/server.js:9:160447)
hastic-server-0 hastic-server     at <anonymous>

![image](https://user-images.githubusercontent.com/7571272/76104436-516b0c00-600e-11ea-844c-4c6489680351.png)

**Comment by jonyrock** [comment]
@tuapuikia sorry for being slow!
@rozetko please help here asap

**Comment by rozetko** [comment]
Hi @tuapuikia 
I've seen that you created issue hastic/hastic-server#878 after this one. Does that mean that this issue is not actual anymore? Please tell us how you fixed it.
